update to resolve error
Traceback (most recent call last):
  File "/home/ec2-user/venv/bin/scrapydweb", line 33, in <module>
    sys.exit(load_entry_point('scrapydweb==1.4.0', 'console_scripts', 'scrapydweb')())
  File "/home/ec2-user/venv/lib/python3.7/site-packages/scrapydweb-1.4.0-py3.7.egg/scrapydweb/run.py", line 32, in main
    app = create_app()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/scrapydweb-1.4.0-py3.7.egg/scrapydweb/__init__.py", line 81, in create_app
    handle_db(app)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/scrapydweb-1.4.0-py3.7.egg/scrapydweb/__init__.py", line 123, in handle_db
    db.create_all()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/flask_sqlalchemy/extension.py", line 868, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/home/ec2-user/venv/lib/python3.7/site-packages/flask_sqlalchemy/extension.py", line 839, in _call_for_binds
    engine = self.engines[key]
  File "/home/ec2-user/venv/lib/python3.7/site-packages/flask_sqlalchemy/extension.py", line 628, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
  File "/home/ec2-user/venv/lib/python3.7/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.